### ISSUE TITLE
Use python2 in python scripts

### ISSUE THREAD

**Issue by fmahnke** [jamie-pate/jstruct#16]
On Arch Linux, the default python version is 3. This causes build errors and can be corrected by specifying the python version in the shebang. Would you change

```
parse/jstruct_parse.py
tests/test_all.py
```
from `#!/usr/bin/env python` to `#!/usr/bin/env python2`

**Comment by jamie-pate** [comment]
I know this pain point, but unfortunately it's not that simple.. I don't think all the other distributions have a python2 link? It's very frustrating!

**Comment by fmahnke** [comment]
good point. I wonder if it could detect the version of python and fail with
a readable error message if incorrect.

Or ultimately, look at the symlinks and preprocess the py files to invoke
the correct one for the distro.

**Comment by jamie-pate** [comment]
I think the best way is to just make the code agnostic to python2/3. There's not much code here, pull requests will be accepted ;)
